### ISSUE TITLE
qt container doesn't start if XAUTHORITY isn't set

### ISSUE THREAD

**Issue by fcrozat** [yast/yast-in-container#16]
When using ssh X forwarding, XAUTHORITY variable might not be set, and it causes qt yast container to fail in entrypoint:
/entrypoint.sh: line 15: XAUTHORITY: unbound variable

I've also noticed XAUTHLOCALHOSTNAME variable should be propagated in the container (it isn't)

**Comment by lslezak** [comment]
Fixed in https://build.opensuse.org/request/show/1005100
